### PR TITLE
Improve example workflow

### PR DESCRIPTION
**Pull request by kevinvanrijn**
This makes 3 changes to the example workflow:

1. Create the commit with `github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>` as the author and `GitHub <noreply@github.com>` as the committer. (Explanation in the comment below.)
Example:
   * https://github.com/kevinvanrijn/github-push-action/commit/a61c74621a72edc93d8c85d49839731480d93985
   * https://github.com/kevinvanrijn/github-push-action/commits/a61c74621a72edc93d8c85d49839731480d93985
2. Do not configure a Git user. (Avoids another step accidentally creating/modifying commits with inaccurate author/committer information.)
3. Do nothing when there are no changes to be committed. (Instead of throwing an error and failing the workflow.)

Opinions?

### CODE REVIEW

**Comment by kevinvanrijn** [comment]
This isn't completely correct yet. Looking at how Dependabot does it, commits are created with the author `dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>` and the committer `GitHub <noreply@github.com>` 

This is how pull requests and commits made through the file uploader/editor on GitHub.com are created as well. The author being the noreply email from the current user and the committer being `GitHub <noreply@github.com>`.

That email Dependabot uses is an actual account: https://api.github.com/users/dependabot-preview%5Bbot%5D

It turns out that GitHub Actions has an account tied to it as well: https://api.github.com/users/github-actions%5Bbot%5D (You'll have seen this account show up if you use `${{ secrets.GITHUB_TOKEN }}` to create a pull request for example.)

So ideally, a commit made by a workflow should be created with `github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>` as the author and `GitHub <noreply@github.com>` as the committer.

**Comment by tenhobi** [comment]
What that `41898282` stands for?

**Comment by kevinvanrijn** [comment]
@tenhobi It's the user id of the Github Actions account/bot.

**Comment by koppor** [comment]
@kevinvanrijn Yes, it would be nice if you added a short note on that. Then, this is good to go!

**Comment by kevinvanrijn** [comment]
@koppor Done.

A quick bit of news from another action. `create-pull-request` is also using the GitHub Actions bot user as its default account since the [v2-beta](https://github.com/peter-evans/create-pull-request/tree/v2-beta#action-inputs).

**Pull request closed without merging**
