### PR TITLE
Add GitHub Enterprise support

### PR DESCRIPTION
**Pull request by ZPascal**
Hi @ad-m,

the corresponding draft PR is a follow-up of the last [PR](https://github.com/ad-m/github-push-action/pull/106) to include the GTE support inside the action. Could you please modify the settings of the repository to make it possible to execute the check also from a fork?

**To-do:**
- [x] Check the GitHub API URL variable from the GitHub context inside the GTE instance.

### CODE REVIEW

**Comment by ad-m** [comment]
> Could you please modify the settings of the repository to make it possible to execute the check also from a fork?

See https://github.com/ad-m/github-push-action/blob/7257a3a6d53a448e11c6f52a112838c57d739d86/.github/workflows/build.yml#L3 . Feel free to provide PR for that.

**Comment by ZPascal** [comment]
Hi @ad-m, I've checked on the GTE instance, if it's possible to use the API URL from the GitHub context. It's definitely the corresponding URL of the API Endpoint of the GitHub Enterprise system.

**Comment by ad-m** [comment]
@ZPascal could you rebase to include changes made in #109 to verify it?

**Comment by ZPascal** [comment]
@ad-m Done. It doesn't seem to work yet. I will look at it in detail later.

**Comment by ad-m** [comment]
I wonder if instead of introducing a new parameter to the action (intended purely for development purposes), it is not enough to write in the pull request template that you should look at the builds on the "push" event on the forking repository, instead of the "pull request" event on the current repository. GitHub-hosted forks should also have GitHub Actions running, so everything audible, so I don't see any reason not to. What do you think about this simplification?

**Comment by ZPascal** [comment]
Hi @ad-m,

sounds validate. I'll modify the PR.

**Comment by ZPascal** [comment]
Hi @ad-m, could we merge the PR?

**Comment by ad-m** [comment]
LGTM

**Pull request merged**
