### PR TITLE
Add note about secrets

### LINKED ISSUE #23: How to set GITHUB_TOKEN?
I'm confused as to how to pass the `GITHUB_TOKEN` to your action. Is it as simple as adding a new  *Personal access token* to `settings -> tokens -> Personal access tokens` to my GitHub account? ^^

### PR DESCRIPTION
**Pull request by tenhobi**
Add a note about using and creating secrets.

Fixes #23

### CODE REVIEW

**Comment by ad-m** [comment]
I would add a sentence about the fact that when accessing the repository from which the GitHub Actions event is triggered, it creates a token for us without any additional configuration. This solves most cases of using the our action and saves reading long documentation.

**Comment by simon300000** [comment]
Note: If we want the push to trigger the actions again or something else, you will need to create you own token, since the GitHub's token does not have permission to do anything else other than push.

**Review by koppor — CHANGES_REQUESTED** [review]
That what @ad-m says. I would also replace "docs" by "GitHub help" to make it clear that the docs is not by this action, but a general one.

**Comment by ZPascal** [comment]
I'm closing the PR because I think the use of tokens, permissions, and secrets is in general already documented [here] (https://github.com/ad-m/github-push-action?tab=readme-ov-file#requirements-and-prerequisites) and in the GitHub upstream documentation. Feel free to reopen it if needed.

**Pull request closed without merging**
