### PR TITLE
feat: Add push to submodules support

### PR DESCRIPTION
**Pull request by ZPascal**
The PR adds push to submodules support

Fix: #152

### CODE REVIEW

**Comment by ZPascal** [comment]
@jackton1 Could you please check the PR?

**Comment by daquinteroflex** [comment]
Hi what's the status of this?

**Comment by ZPascal** [comment]
@daquinteroflex I need a review :)

**Comment by jackton1** [comment]
Hi @ZPascal, sorry for the delay on this. I’ll take a look at this today.

**Review by jackton1 — APPROVED** [review]

**Pull request merged**
